### PR TITLE
Trigger github actions rerun.

### PR DESCRIPTION
**Pull request by sv2518**
I think master is currently failing in the installation of mpi4py. One can see that in Connor's and the loopy sprint branch. Opening a PR to rerun the actions on master to double-check if what I am saying is indeed the case.

### CODE REVIEW

**Comment by connorjward** [comment]
It's the petsc4py install that's failing not mpi4py.

**Comment by wence-** [comment]
`Cloning https://github.com/firedrakeproject/petsc4py.git (to revision firedrake)`

The actions workflow needs to be updated to grab petsc4py from the petsc source tree.

I note also that currently we're installing petsc from pip, rather than the firedrake petsc clone. So plausibly that wants reworked too.

**Comment by connorjward** [comment]
I've agreed to take this on. Do we need any special configure options for PETSc when we build it or is the default (plus petsc4py) sufficient?

**Comment by wence-** [comment]
Pretty sure default is sufficient (we're just doing `pip install petsc` right now as far as I recall). Probably `--with-shared-libraries=1 --with-debugging=1` is a good choice.

**Comment by sv2518** [comment]
A fix got merged in f1daf214c1eedd86a37aaada2565c4d442c8ebbf.

**Pull request closed without merging**
