### PR TITLE
Replace deprecated new_hash

### PR DESCRIPTION
**Pull request by connorjward**

### CODE REVIEW

**Comment by ksagiyam** [comment]
This change itself looks good to me, but tests are failing (probably because it uses current `firedrake-project/loopy`).

**Comment by connorjward** [comment]
Yeah that's why. What I've done shouldn't affect anything at all. `new_hash` was just calling `sha256` under the hood anyway.

**Comment by inducer** [comment]
Oh yikes. Sorry! I had new idea you guys were relying on that. :grimacing:

**Comment by wence-** [comment]
Neither did we, I think

**Comment by inducer** [comment]
FYI https://github.com/inducer/pytools/pull/60

**Pull request merged**
