### PR TITLE
add ComposedMap

### PR DESCRIPTION
**Pull request by ksagiyam**

### CODE REVIEW

**Comment by ReubenHill** [comment]
What's this for? I presume it could replace my manual effort at https://github.com/firedrakeproject/firedrake/blob/ee720d61991e7f04004847dce79844771fad6e2b/firedrake/interpolation.py#L460-L509?

**Comment by ksagiyam** [comment]
I need this for submesh. I think you can use `op2.ComposedMap(map2, map1)` for `composed_map(map1, map2)` except for the real function case.

**Comment by ReubenHill** [comment]
> 

Do you implement caching? Also why would the real function case not work?

**Comment by ksagiyam** [comment]
I meant those lines in your code:
```
    if map2 is None:
        # Real function space case
        return None
```

This is not cached now like other types of maps.

**Review by dham — CHANGES_REQUESTED** [review]
Please put an extruded test here, and swap out Reuben's code in Firedrake (which will get us a parallel test).

**Review by dham — APPROVED** [review]

**Comment by ksagiyam** [comment]
Rebased. Thank you!

**Pull request merged**
