### PR TITLE
utils: Backport cached property from functools

### PR DESCRIPTION
**Pull request by wence-**
Fixes some corner cases of decorator composition with cached_property (c.f. firedrakeproject/firedrake#1567)

### CODE REVIEW

**Comment by wence-** [comment]
OK, this is more complicated, because it requires Python 3.6. (released Dec 2016). I guess that's a bit recent (we presently require 3.5).

**Comment by nbouziani** [comment]
Could we not just let the hacking name workaround?

**Comment by sv2518** [comment]
Looks like firedrakeproject/firedrake#1567 already got merged, is this merge request still active?

**Comment by wence-** [comment]
Probably not. Sorry for the delay.

**Pull request closed without merging**
