### PR TITLE
composed map: add permute to kwarg

### PR DESCRIPTION
**Pull request by ksagiyam**
https://github.com/firedrakeproject/firedrake/pull/3634

I found this bug when using the submesh branch with BCs on vector components. It is hard to test with our current usage of ComposedMap in Firedrake. I wonder this can just go in.

### CODE REVIEW

**Review by connorjward — APPROVED** [review]
Looks fine to me. Happy for this to be merged assuming Firedrake tests pass.

**Comment by ksagiyam** [comment]
Actually, a pyop2 test failed, which suggested a better fix. Could you have a look again?

**Comment by ksagiyam** [comment]
Rerunning Firedrake CI.

**Comment by ksagiyam** [comment]
Indeed. Rerunning Firedrake CI.

**Review by connorjward — APPROVED** [review]

**Pull request merged**
