### PR TITLE
make sure is_top is false for non-extruded maps

### PR DESCRIPTION
**Pull request by dham**

### CODE REVIEW

**Comment by wence-** [comment]
I guess this is the minimal change to get things to work for firedrakeproject/firedrake#479

**Comment by dham** [comment]
Basically, yes.I think it's also the Right Thing because we're directly checking if the relevant map is extruded.

**Comment by kynan** [comment]
Seems sensible.

**Comment by kynan** [comment]
Is this good to merge @wence-?

**Pull request merged**
